In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import date, datetime
import seaborn as sb
from matplotlib import rcParams

In [72]:
data=pd.read_csv("C:\\Users\\Nacho\\Downloads\\HENRY\\Proyectos\\Proyectos_Propios\\Pakistan Largest Ecommerce Dataset.csv", decimal=".",thousands=",")
data

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (1,2,3,7,8,9,11,12,13,14,17,18,19) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,Month,Customer Since,M-Y,FY,Customer ID,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,211131.0,complete,7/1/2016,kreations_YI 06-L,1950.0,1.0,1950.0,100147443,Women's Fashion,\N,...,7.0,2016-7,7-2016,FY17,1.0,NaN,NaN,NaN,NaN,NaN
1,211133.0,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1.0,240.0,100147444,Beauty & Grooming,\N,...,7.0,2016-7,7-2016,FY17,2.0,NaN,NaN,NaN,NaN,NaN
2,211134.0,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1.0,2450.0,100147445,Women's Fashion,\N,...,7.0,2016-7,7-2016,FY17,3.0,NaN,NaN,NaN,NaN,NaN
3,211135.0,complete,7/1/2016,kcc_krone deal,360.0,1.0,60.0,100147446,Beauty & Grooming,R-FSD-52352,...,7.0,2016-7,7-2016,FY17,4.0,NaN,NaN,NaN,NaN,NaN
4,211136.0,order_refunded,7/1/2016,BK7010400AG,555.0,2.0,1110.0,100147447,Soghaat,\N,...,7.0,2016-7,7-2016,FY17,5.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
data = data.dropna(how='all')
data

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,Month,Customer Since,M-Y,FY,Customer ID,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,211131.0,complete,7/1/2016,kreations_YI 06-L,1950.0,1.0,1950.0,100147443,Women's Fashion,\N,...,7.0,2016-7,7-2016,FY17,1.0,NaN,NaN,NaN,NaN,NaN
1,211133.0,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1.0,240.0,100147444,Beauty & Grooming,\N,...,7.0,2016-7,7-2016,FY17,2.0,NaN,NaN,NaN,NaN,NaN
2,211134.0,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1.0,2450.0,100147445,Women's Fashion,\N,...,7.0,2016-7,7-2016,FY17,3.0,NaN,NaN,NaN,NaN,NaN
3,211135.0,complete,7/1/2016,kcc_krone deal,360.0,1.0,60.0,100147446,Beauty & Grooming,R-FSD-52352,...,7.0,2016-7,7-2016,FY17,4.0,NaN,NaN,NaN,NaN,NaN
4,211136.0,order_refunded,7/1/2016,BK7010400AG,555.0,2.0,1110.0,100147447,Soghaat,\N,...,7.0,2016-7,7-2016,FY17,5.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584519,905204.0,cod,8/28/2018,WOFSCE5AE00357AECDE,699.0,1.0,849.0,100562385,Women's Fashion,NaN,...,8.0,2018-8,8-2018,FY19,115320.0,NaN,NaN,NaN,NaN,NaN
584520,905205.0,processing,8/28/2018,MATHUA5AF70A7D1E50A,35599.0,1.0,35899.0,100562386,Mobiles & Tablets,NaN,...,8.0,2018-8,8-2018,FY19,115326.0,NaN,NaN,NaN,NaN,NaN
584521,905206.0,processing,8/28/2018,MATSAM5B6D7208C6D30,129999.0,2.0,652178.0,100562387,Mobiles & Tablets,NaN,...,8.0,2018-7,8-2018,FY19,113474.0,NaN,NaN,NaN,NaN,NaN
584522,905207.0,processing,8/28/2018,MATSAM5B1509B4696EA,87300.0,2.0,652178.0,100562387,Mobiles & Tablets,NaN,...,8.0,2018-7,8-2018,FY19,113474.0,NaN,NaN,NaN,NaN,NaN
584523,905208.0,processing,8/28/2018,MATSAM5B10F91A9B6AB,108640.0,2.0,652178.0,100562387,Mobiles & Tablets,NaN,...,8.0,2018-7,8-2018,FY19,113474.0,NaN,NaN,NaN,NaN,NaN

In [74]:
data=data.iloc[:,:-5]
data

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,211131.0,complete,7/1/2016,kreations_YI 06-L,1950.0,1.0,1950.0,100147443,Women's Fashion,\N,...,cod,7/1/2016,#REF!,"1,950",2016.0,7.0,2016-7,7-2016,FY17,1.0
1,211133.0,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1.0,240.0,100147444,Beauty & Grooming,\N,...,cod,7/1/2016,Gross,240,2016.0,7.0,2016-7,7-2016,FY17,2.0
2,211134.0,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1.0,2450.0,100147445,Women's Fashion,\N,...,cod,7/1/2016,Gross,"2,450",2016.0,7.0,2016-7,7-2016,FY17,3.0
3,211135.0,complete,7/1/2016,kcc_krone deal,360.0,1.0,60.0,100147446,Beauty & Grooming,R-FSD-52352,...,cod,7/1/2016,Net,360,2016.0,7.0,2016-7,7-2016,FY17,4.0
4,211136.0,order_refunded,7/1/2016,BK7010400AG,555.0,2.0,1110.0,100147447,Soghaat,\N,...,cod,7/1/2016,Valid,"1,110",2016.0,7.0,2016-7,7-2016,FY17,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584519,905204.0,cod,8/28/2018,WOFSCE5AE00357AECDE,699.0,1.0,849.0,100562385,Women's Fashion,NaN,...,cod,8/28/2018,Valid,699,2018.0,8.0,2018-8,8-2018,FY19,115320.0
584520,905205.0,processing,8/28/2018,MATHUA5AF70A7D1E50A,35599.0,1.0,35899.0,100562386,Mobiles & Tablets,NaN,...,bankalfalah,8/28/2018,Gross,"35,599",2018.0,8.0,2018-8,8-2018,FY19,115326.0
584521,905206.0,processing,8/28/2018,MATSAM5B6D7208C6D30,129999.0,2.0,652178.0,100562387,Mobiles & Tablets,NaN,...,bankalfalah,8/28/2018,Gross,"259,998",2018.0,8.0,2018-7,8-2018,FY19,113474.0
584522,905207.0,processing,8/28/2018,MATSAM5B1509B4696EA,87300.0,2.0,652178.0,100562387,Mobiles & Tablets,NaN,...,bankalfalah,8/28/2018,Gross,"174,600",2018.0,8.0,2018-7,8-2018,FY19,113474.0
584523,905208.0,processing,8/28/2018,MATSAM5B10F91A9B6AB,108640.0,2.0,652178.0,100562387,Mobiles & Tablets,NaN,...,bankalfalah,8/28/2018,Gross,"217,280",2018.0,8.0,2018-7,8-2018,FY19,113474.0

In [75]:
data.iloc[:,8:]

,category_name_1,sales_commission_code,discount_amount,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,Women's Fashion,\N,0.0,cod,7/1/2016,#REF!,"1,950",2016.0,7.0,2016-7,7-2016,FY17,1.0
1,Beauty & Grooming,\N,0.0,cod,7/1/2016,Gross,240,2016.0,7.0,2016-7,7-2016,FY17,2.0
2,Women's Fashion,\N,0.0,cod,7/1/2016,Gross,"2,450",2016.0,7.0,2016-7,7-2016,FY17,3.0
3,Beauty & Grooming,R-FSD-52352,300.0,cod,7/1/2016,Net,360,2016.0,7.0,2016-7,7-2016,FY17,4.0
4,Soghaat,\N,0.0,cod,7/1/2016,Valid,"1,110",2016.0,7.0,2016-7,7-2016,FY17,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
584519,Women's Fashion,NaN,0.0,cod,8/28/2018,Valid,699,2018.0,8.0,2018-8,8-2018,FY19,115320.0
584520,Mobiles & Tablets,NaN,0.0,bankalfalah,8/28/2018,Gross,"35,599",2018.0,8.0,2018-8,8-2018,FY19,115326.0
584521,Mobiles & Tablets,NaN,0.0,bankalfalah,8/28/2018,Gross,"259,998",2018.0,8.0,2018-7,8-2018,FY19,113474.0
584522,Mobiles & Tablets,NaN,0.0,bankalfalah,8/28/2018,Gross,"174,600",2018.0,8.0,2018-7,8-2018,FY19,113474.0
584523,Mobiles & Tablets,NaN,0.0,bankalfalah,8/28/2018,Gross,"217,280",2018.0,8.0,2018-7,8-2018,FY19,113474.0

In [76]:
columnas=["Id_Item","Estado_Compra","Fecha","Direccion","Precio","Cantidad","Total","Id","Categoria_1","Comision","Descuento","Metodo_Pago","Fecha_Trabajo","BI_Status","MV","Año","Mes","Cliente_Desde","M-Y","FY","Id_Cliente"]
data.columns=columnas
data

,Id_Item,Estado_Compra,Fecha,Direccion,Precio,Cantidad,Total,Id,Categoria_1,Comision,...,Metodo_Pago,Fecha_Trabajo,BI_Status,MV,Año,Mes,Cliente_Desde,M-Y,FY,Id_Cliente
0,211131.0,complete,7/1/2016,kreations_YI 06-L,1950.0,1.0,1950.0,100147443,Women's Fashion,\N,...,cod,7/1/2016,#REF!,"1,950",2016.0,7.0,2016-7,7-2016,FY17,1.0
1,211133.0,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1.0,240.0,100147444,Beauty & Grooming,\N,...,cod,7/1/2016,Gross,240,2016.0,7.0,2016-7,7-2016,FY17,2.0
2,211134.0,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1.0,2450.0,100147445,Women's Fashion,\N,...,cod,7/1/2016,Gross,"2,450",2016.0,7.0,2016-7,7-2016,FY17,3.0
3,211135.0,complete,7/1/2016,kcc_krone deal,360.0,1.0,60.0,100147446,Beauty & Grooming,R-FSD-52352,...,cod,7/1/2016,Net,360,2016.0,7.0,2016-7,7-2016,FY17,4.0
4,211136.0,order_refunded,7/1/2016,BK7010400AG,555.0,2.0,1110.0,100147447,Soghaat,\N,...,cod,7/1/2016,Valid,"1,110",2016.0,7.0,2016-7,7-2016,FY17,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584519,905204.0,cod,8/28/2018,WOFSCE5AE00357AECDE,699.0,1.0,849.0,100562385,Women's Fashion,NaN,...,cod,8/28/2018,Valid,699,2018.0,8.0,2018-8,8-2018,FY19,115320.0
584520,905205.0,processing,8/28/2018,MATHUA5AF70A7D1E50A,35599.0,1.0,35899.0,100562386,Mobiles & Tablets,NaN,...,bankalfalah,8/28/2018,Gross,"35,599",2018.0,8.0,2018-8,8-2018,FY19,115326.0
584521,905206.0,processing,8/28/2018,MATSAM5B6D7208C6D30,129999.0,2.0,652178.0,100562387,Mobiles & Tablets,NaN,...,bankalfalah,8/28/2018,Gross,"259,998",2018.0,8.0,2018-7,8-2018,FY19,113474.0
584522,905207.0,processing,8/28/2018,MATSAM5B1509B4696EA,87300.0,2.0,652178.0,100562387,Mobiles & Tablets,NaN,...,bankalfalah,8/28/2018,Gross,"174,600",2018.0,8.0,2018-7,8-2018,FY19,113474.0
584523,905208.0,processing,8/28/2018,MATSAM5B10F91A9B6AB,108640.0,2.0,652178.0,100562387,Mobiles & Tablets,NaN,...,bankalfalah,8/28/2018,Gross,"217,280",2018.0,8.0,2018-7,8-2018,FY19,113474.0

In [77]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 584524 entries, 0 to 584523
Data columns (total 21 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Id_Item        584524 non-null  float64
 1   Estado_Compra  584509 non-null  object
 2   Fecha          584524 non-null  object
 3   Direccion      584504 non-null  object
 4   Precio         584524 non-null  float64
 5   Cantidad       584524 non-null  float64
 6   Total          584524 non-null  float64
 7   Id             584524 non-null  object
 8   Categoria_1    584360 non-null  object
 9   Comision       447349 non-null  object
 10  Descuento      584524 non-null  float64
 11  Metodo_Pago    584524 non-null  object
 12  Fecha_Trabajo  584524 non-null  object
 13  BI_Status      584524 non-null  object
 14  MV             584524 non-null  object
 15  Año            584524 non-null  float64
 16  Mes            584524 non-null  float64
 17  Cliente_Desde  584513 non-null  object
 18  M-Y            584524 non-null  object
 19  FY             584524 non-null  object
 20  Id_Cliente     584513 non-null  float64
dtypes: float64(8), object(13)
memory usage: 98.1+ MB

In [78]:
data["Id_Item"]=data["Id_Item"].astype(int)
data["Estado_Compra"]=data["Estado_Compra"].astype(str)
data['Fecha'] = pd.to_datetime(data['Fecha']).dt.date
data["Direccion"]=data["Direccion"].astype(str)
data["Precio"]=data["Precio"].astype(float)
data["Cantidad"]=data["Cantidad"].fillna(0)
data["Cantidad"]=data["Cantidad"].astype(int)
data["Total"]=data["Total"].astype(float)
data["Id"]=data["Id"].astype(str)
data["Categoria_1"]=data["Categoria_1"].astype(str)
data["Comision"]=data["Comision"].astype(str)
data["Descuento"]=data["Descuento"].astype(float)
data["Metodo_Pago"]=data["Metodo_Pago"].astype(str)
data['Fecha_Trabajo'] = pd.to_datetime(data['Fecha_Trabajo']).dt.date
data["MV"]=data["MV"].astype(str)
data["MV"]=[x.replace('-',"0") for x in data["MV"]]
data["MV"]=[x.replace(',','') for x in data["MV"]]
data["MV"]=data["MV"].astype(float)
data["Año"]=data["Año"].astype(float)
data["Año"]=data["Año"].astype(int)
data["Mes"]=data["Mes"].fillna(0)
data["Mes"]=data["Mes"].astype(int)
data["Cliente_Desde"]=data["Cliente_Desde"].astype(str)
data["Id_Cliente"]=data["Id_Cliente"].astype(str)

In [79]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 584524 entries, 0 to 584523
Data columns (total 21 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Id_Item        584524 non-null  int64
 1   Estado_Compra  584524 non-null  object
 2   Fecha          584524 non-null  object
 3   Direccion      584524 non-null  object
 4   Precio         584524 non-null  float64
 5   Cantidad       584524 non-null  int64
 6   Total          584524 non-null  float64
 7   Id             584524 non-null  object
 8   Categoria_1    584524 non-null  object
 9   Comision       584524 non-null  object
 10  Descuento      584524 non-null  float64
 11  Metodo_Pago    584524 non-null  object
 12  Fecha_Trabajo  584524 non-null  object
 13  BI_Status      584524 non-null  object
 14  MV             584524 non-null  float64
 15  Año            584524 non-null  int64
 16  Mes            584524 non-null  int64
 17  Cliente_Desde  584524 non-null  object
 18  M-Y            584524 non-null  object
 19  FY             584524 non-null  object
 20  Id_Cliente     584524 non-null  object
dtypes: float64(4), int64(4), object(13)
memory usage: 98.1+ MB

In [80]:
data['Estado_Compra'].unique().tolist()

['complete',
 'canceled',
 'order_refunded',
 'received',
 'refund',
 'closed',
 'fraud',
 'holded',
 'exchange',
 'pending_paypal',
 'paid',
 '\\N',
 'cod',
 'pending',
 'nan',
 'processing',
 'payment_review']

In [81]:
data[data["Estado_Compra"]=="\\N"]

,Id_Item,Estado_Compra,Fecha,Direccion,Precio,Cantidad,Total,Id,Categoria_1,Comision,...,Metodo_Pago,Fecha_Trabajo,BI_Status,MV,Año,Mes,Cliente_Desde,M-Y,FY,Id_Cliente
255520,526623,\N,2017-07-03,test-product-3,3.0,2,231.0,100332005,\N,\N,...,cod,2017-07-03,Gross,6.0,2017,7,2016-7,7-2017,FY18,1423.0
255521,526624,\N,2017-07-03,test-product,75.0,1,231.0,100332005,\N,\N,...,cod,2017-07-03,Gross,75.0,2017,7,2016-7,7-2017,FY18,1423.0
255624,526754,\N,2017-07-03,test-product-3,3.0,2,231.0,100332075,\N,\N,...,cod,2017-07-03,Gross,6.0,2017,7,2016-7,7-2017,FY18,1423.0
255625,526755,\N,2017-07-03,test-product,75.0,1,231.0,100332075,\N,\N,...,cod,2017-07-03,Gross,75.0,2017,7,2016-7,7-2017,FY18,1423.0

In [82]:
data[data["Estado_Compra"]=="nan"]

,Id_Item,Estado_Compra,Fecha,Direccion,Precio,Cantidad,Total,Id,Categoria_1,Comision,...,Metodo_Pago,Fecha_Trabajo,BI_Status,MV,Año,Mes,Cliente_Desde,M-Y,FY,Id_Cliente
477519,783751,nan,2018-03-15,OTHPCB5A7D8A0BD10E8,8000.0,1,8000.0,100479380,Others,nan,...,cod,2018-03-15,Gross,8000.0,2018,3,2018-3,3-2018,FY18,95141.0
513736,827187,nan,2018-04-16,KABOXF5ABCC75C7E2F7-32,370.0,1,2707.0,100513933,Kids & Baby,nan,...,cod,2018-04-16,Gross,370.0,2018,4,2018-4,4-2018,FY18,105059.0
513737,827189,nan,2018-04-16,KABSHO5AA77C331466F-11-13 Years,473.0,1,2707.0,100513933,Kids & Baby,nan,...,cod,2018-04-16,Gross,473.0,2018,4,2018-4,4-2018,FY18,105059.0
513738,827191,nan,2018-04-16,KABBIN5A93E074C501A-8-9 Years,749.0,1,2707.0,100513933,Kids & Baby,nan,...,cod,2018-04-16,Gross,749.0,2018,4,2018-4,4-2018,FY18,105059.0
513739,827193,nan,2018-04-16,KABLIT59AC117FD51C4-12-13 Years,692.0,1,2707.0,100513933,Kids & Baby,nan,...,cod,2018-04-16,Gross,692.0,2018,4,2018-4,4-2018,FY18,105059.0
513740,827195,nan,2018-04-16,KABCOL5AB2B8019805C-8-9 Years,423.0,1,2707.0,100513933,Kids & Baby,nan,...,cod,2018-04-16,Gross,423.0,2018,4,2018-4,4-2018,FY18,105059.0
518706,832777,nan,2018-04-30,ENTCLI5A5DD7D800D6E,6042.0,1,6042.0,100517141,Entertainment,nan,...,cod,2018-04-30,Gross,6042.0,2018,4,2018-4,4-2018,FY18,106036.0
532965,848003,nan,2018-05-14,MATINF5AE310D2D7A1A,13950.0,1,13950.0,100527966,Mobiles & Tablets,nan,...,cod,2018-05-14,Gross,13950.0,2018,5,2018-4,5-2018,FY18,105319.0
542146,857829,nan,2018-05-25,ROO5AE983F2751EA,2280.0,1,2280.0,100534786,Superstore,nan,...,cod,2018-05-25,Gross,2280.0,2018,5,2018-5,5-2018,FY18,109580.0
554962,872154,nan,2018-06-15,BAGPHI5AA665985A58E,2900.0,1,949.0,100542483,Beauty & Grooming,nan,...,bankalfalah,2018-06-15,Gross,2900.0,2018,6,2018-5,6-2018,FY18,109420.0
556575,873867,nan,2018-06-20,SEH59F33B639C948,13998.0,1,13998.0,100543636,Superstore,nan,...,cod,2018-06-20,Gross,13998.0,2018,6,2018-6,6-2018,FY18,111346.0
562052,879771,nan,2018-07-02,MEFTHE5ABD1716014D5-XL,0.0,1,150.0,100547232,Men's Fashion,nan,...,cod,2018-07-02,Gross,0.0,2018,7,2018-7,7-2018,FY19,112111.0
566295,884706,nan,2018-07-13,OTHOTH5A097CEF981C2,100.0,1,250.0,100550314,Others,nan,...,cod,2018-07-13,Gross,100.0,2018,7,2018-6,7-2018,FY19,111651.0
566296,884707,nan,2018-07-13,OTHOTH5A097CEF981C2,100.0,2,350.0,100550315,Others,nan,...,cod,2018-07-13,Gross,200.0,2018,7,2018-6,7-2018,FY19,111651.0
568050,886679,nan,2018-07-18,OTHOTH5A097CEF981C2,100.0,4,550.0,100551487,Others,nan,...,cod,2018-07-18,Gross,400.0,2018,7,2018-6,7-2018,FY19,111651.0

In [83]:
data["Estado_Compra"]=data["Estado_Compra"].replace("nan","No Data")
data["Estado_Compra"]=data["Estado_Compra"].replace("\\N","No Data")

In [84]:
data['Estado_Compra'].unique().tolist()

['complete',
 'canceled',
 'order_refunded',
 'received',
 'refund',
 'closed',
 'fraud',
 'holded',
 'exchange',
 'pending_paypal',
 'paid',
 'No Data',
 'cod',
 'pending',
 'processing',
 'payment_review']

In [85]:
data['Direccion'].unique().tolist()

['kreations_YI 06-L',
 'kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Body Spray Free',
 'Ego_UP0017-999-MR0',
 'kcc_krone deal',
 'BK7010400AG',
 'UK_Namkino All In One 200 Gms',
 'UK_Namkino Mix Nimco 400 Gms',
 'Apple iPhone 6S 64GB',
 'GFC_Pedestal Myga Cross Base (Special Guard) 24"',
 'BK1070200PL',
 'BK1130200CF',
 'kcc_Sultanat',
 'kcc_glamour deal',
 'Assetmen_MD-346-M',
 'cr_DATES WITH CASHEW-400 GM',
 'UK_Gift Box Mix Dry Fruit Sweets 500 Gms',
 'itter_AB 1199',
 'RL_B005',
 'bed&rest_S7',
 'L&L_LLHLE8224S',
 'J&J_JJR-4',
 'J&J_JJR-20',
 'D Lend a Helping Hand',
 'Mochika_M0001112-12',
 'Mochika_M0001112-8',
 'SKMT_Blood Test',
 'SKMT_Medicine',
 'sputnik_701/5-11',
 'Ctees-Black Zip- Up Hoodie-XL',
 'Samsung Galaxy J5',
 'Veet_4',
 'RS_Gulab jaman Tin',
 'cr_PEANUT SALTY-200 GM',
 'Oriflame_21557',
 'JBS_TAT-128',
 'Ajmery_BRR-590-M',
 'HOS_GUCFW75',
 'Lexon_LL116B-Blue',
 'kcc_Fantasy Perfumed Talcum Powder-200gm',
 '2Zee_SC6',
 'Q MOBILE Noir X20',
 'rehaab_RJ160047',
 'Farah_3-B',
 'RS_Sohan Halwa Tin',
 'UK_Soan Papdi Original 250 Gms',
 'UK_Gift Box Soghaat 500 Gms',
 'RS_Double Delight',
 'Al Muhafiz Sohan Halwa Almond',
 'UK_Gift Box Baklawa 500 Gms',
 'sputnik_2146/6-8',
 'kkc_Kingtox 450ml Classic Green All Insect Killer Spray',
 'Al Muhafiz Sohan Halwa Walnut',
 'RS_Honey Dry Fruit Halwa',
 'itter_AB 1214',
 'Eco Star_40U557',
 'Orient_OR-6057 GX LGFD LV',
 'HOS_JPGCW100',
 'kkc_Jasmine King Air Freshener',
 'asimjofaeanew_5A',
 'ajmery_F9-981',
 'hijabh_JILBAB-C (1)-52x',
 'noritake_NTM163M',
 'RS_Habshi Halwa Tin',
 'sentiments_WRK1612',
 'bata_comfit-8613714-43-9',
 'UK_Namkino Mix Nimco 8 Pcs Gift Pack',
 'Inoxy_Inoxy Hair Miracle Elixir',
 'RS_Chum Chum Tin',
 'Dany_AUK-650 ',
 'urban_ PT004-L',
 'jackpot_JP-7999',
 'UK_Gift Box Pistachio Delight 500 Gms',
 'test_tcsconnect',
 'sst_Lyquin-Regular fit-Large',
 'Fcafe_11777-L',
 'LC_359547105042',
 'LC_3349668508587',
 'RS_pheni Desi Ghee 1 kg ',
 'UK_Gulab Jamun Tin Pack 500 Gms',
 'UK_Chum Chum Tin Pack  500 Gms',
 'UK_Namkino Mix Nimco 200 Gms',
 'sentiments_Ferrero Rocher Gift Box',
 'EGO_E02377-SML-BG00-S',
 'darzee_DP-234-B-Pink-15-M',
 'Q MOBILE Noir W7',
 'RS_Kaju Barfi',
 'RS_cake rusk',
 'HR_Bhel Puri 200g',
 'UK_Gift Box Almond Delight 500 Gms',
 'UK_Soan Papdi 500 Gms',
 'Huawei Honor 4C',
 'bata_comfit-8614096-43-9',
 'bata_comfit-8614096-41-7',
 'UK_Gift Box Baklawa 300 Gms',
 'UK_Namkino Daal Moth Classic 160 Gms',
 'kcc_Bold Pocket Perfume',
 'UK_Cake Rusk Original 150 Gms',
 'itter_AB 1207',
 'Samsung Galaxy J7',
 'Dany_AUK 55 ',
 'anex_2028',
 'Atiqa_ACFP-01',
 'UK_Soan Papdi Orange 250 Gms',
 'kcc_Xtreme Classical Men Shower Gel',
 'UK_Tea Rusk Regular 220 Gms',
 'kcc_Glow',
 'emo_HST-17030-B-M',
 'Dany_Powerbank Pb- 41',
 'Getiit_Joy',
 'MYWALET_MW-012-BLACK',
 'sstop_Mini AIr Conditioner',
 'Huawei_Huawei B2 Talk Band',
 'cr_DATES WITH CASHEW-200 GM',
 'cr_DATES WITH WALNUT-200 GM',
 'Xenium_TG-201653',
 'Xenium_TG-2016132',
 'Xenium_MBC-2016130',
 'ESPICO_Sports Bra-Skin-Free size',
 'PucaM_FLASH-BLACK-45',
 'Huawei Y221',
 'Rabia_1-A',
 'kkc_Rose Oasis Prickly Heat Powder',
 'cr_MUZAFTI IRANI (500GM)',
 'test_tcsconnect1',
 'Test Hazir Product 2-Karachi',
 'Audionic_B-710',
 'Haier M106',
 'GBH-GL245-GOLD-7',
 'itter_AB1263',
 'GBH-GL226-PINK-8',
 'sstop_3dcreenwithspeakers',
 'UK_Namkino Khat Mitha Mix 400 Gms',
 'UK_Sohan Halwa Tin Pack 400 Gms',
 'bata_leena-5178202-38-5',
 'KC_209 White-M',
 'mm_AG-1038c',
 '3m_DC272923871',
 'MEGUIAR_G12711',
 'MEGUIAR_G3503',
 'MEGUIAR_X3070',
 'BFk_Denim Jeans with Gallace for Boys |OF67-3-4 yrs',
 'RS_Soan Papri-250gm',
 'kcc_lush',
 'HR_Pani Puri 360g',
 'kcc_active',
 'kcc_Xtreme Mantastic Men Shower Gels',
 'Rajesh_RAJ033',
 'ajmery_AJ-123-L',
 'mitsubishi_1.5 ton SRC 18CLK',
 'Dany_Genius Tab G7 Metallica ',
 'bata_leena-6618940-39-6',
 'gree_12CZ8',
 'Teenz_B-0541',
 'Emo_SS-22057-11',
 'sapil_Sapil Disclosure Men 100ML',
 'MYWALET_MW-002-D-BROWN',
 'kcc_Bakheer Pocket Perfume',
 'kcc_Oudh Pocket Perfume',
 'kcc_Asool Pocket Perfume',
 'Veet_3',
 'itter_AB 1141',
 'Veet_5',
 'sst_Logic  3-Regular fit-Medium',
 'kkc_Hayam King Air Freshener',
 'sapil_Sapil Passion Women 200ML',
 'Dynasty_Classic Cotton-Skin',
 'WE_ni72_parrot-veet-gift',
 'cos_prfume_9',
 'Trans_LW 509B ',
 'LC_3595471021182',
 'shoppingmania_18k Gold Filled Blue Ruby Necklace & Earrings',
 'Teenz_R-0172-7',
 'HOS_RLRW100',
 'AKL_A131131293_FC-12',
 'MYWALET_MW-014-BLACK',
 'Xenium_WA-201611',
 'pak_B-32',
 'rub_Rubian_VR-Box With Remote',
 'kkc_ Icy Menthol Oasis Prickly Heat Powder',
 'shoppingmania_Enamel Retro NecklaceTitanic Heart Crystal Pendant',
 'Teenz_E-1574 silver',
 'emo_HSP-17043-M',
 'Emo_HST-28676-L',
 'RS_Pheni Desi Ghee 500gm',
 'Huawei Honor 4X',
 'AUDIONIC6-954217-513546',
 'bata_leena-5176214-40-7',
 'Tiraaz_Tm-01-001-M',
 'Audionic_B-334',
 'kcc_effect',
 'bata_wein-8734881-44-10',
 'CU-0107-Slim Fit Small',
 'itter_AB 1122',
 'itter_AB 1126',
 'itter_AB 1125',
 'HR_Soan Papdi 500g',
 'stitchers_TnT 012-L',
 'Ego_E02437-GN0-Green-XSM',
 'Ref-Queen 5041-Black-38',
 'B-power_8282391-44',
 'dawlance_Health Zone Plus 30 - 1.5 Ton Air Conditioner',
 'vitamin_Vita White',
 'Rajesh_RAJ61',
 'BO_topfastRc-yellow',
 'Rajesh_Ben 10 Rail',
 'kcc_jazzy',
 'Samsung Galaxy S7 Edge',
 'BO_racingjeeoRC-silver',
 'Rajesh_Green Ben 10 Educational Computer',
 'BO_nonRC-Jeep-Red',
 'BO_blocks-small-1',
 'osaka_3.5W LED BULB',
 'Mochika_M0001125-8',
 'Mochika_M0001125-12',
 'Dany256564981654986456',
 'Dany72474879523146357896',
 'cr_REWARI CHAKWAL',
 'AKL_A131128850_SS-19_Blue',
 'ihijab_PN025',
 'bed&rest_Danika 3D',
 'VITAMIN_KOJIC ACID WHITENING CREAM',
 'PHILIPS_HP8600_32',
 'b&d_Citrus Juicer CJ650   ',
 'vitamin_Kojic Acid Whitening Face Wash',
 'E TCF_Educate a child for a month-PKR 1250',
 'bata_comfit-8614737-42-8',
 'kcc_Cool Pocket Perfume',
 'UK_Gift Box Mix Sweets 500 Gms',
 'Dynasty_Dynasty Spark-Off-White',
 'mitsubhisi_1.0 Ton - SRK-13CMK',
 'Dynasty_Dynasty Spark-Grey',
 'UK_Bangali Rasgulla Tin Pack  500 Gms',
 'UK_Namkino Masala Sev 200 Gms',
 'UK_ Namkino Daal Moong 200 Gms',
 'UK_Bhel Puri 200 Gms',
 'UK_Namkino Khat Mitha Mix 200 Gms',
 'Ctees_Paris Butterflies Pouch',
 'bata_comfit-8644502-42-8',
 'Emo_SS-18755-41',
 'itter_AB 1211',
 'WE_TU2',
 'bata_bags_9064517-Brown',
 'sapil_Sapil Nancy Women 200ML',
 'ajmery_TA-3',
 'Emo-CT-24304 Green 8 Pocket Cargo Trouser-34',
 'UK_Kala Jamun Tin Pack 500 Gms',
 'tram_TT25125100',
 'US-MSK-6-pink-2T',
 'ihijab_PN041',
 'asimjofaeanew_4A',
 'tram_TT25128100',
 'jackpot_JP-902',
 'sanasafinaz_march16_10B-Nationwide Delivery',
 'HR_Punjabi Tadka 200g',
 'UK_Namkino Crunchy Nut Mix 200 Gms',
 'Royal_Energy saver Fan 56 New Model',
 'emo_Emo-MH-25104-M',
 'urban_URT0025 -L',
 'Emo-CT-24302 Brown Twill Cotton 8 Pocket Cargo Trouser-30',
 'emo_Emo-MH-19734-M',
 'UK_Namkino Mix Nimco 5 Pcs Gift Pack',
 'dawlance_Refrigerator 9170WB Energy Saver',
 'UK_Bangali Chum Chum Tin Pack  500 Gms',
 'bed&rest_B3',
 'tram_TT23080083',
 'ajmery_BAT-3-S',
 'UC_Dark Navy Plain Polo-XL',
 'UC_Rust Plain Polo-XL',
 'UC_Purple Plain Polo-XL',
 'UC_Lagoon Plain Polo-XL',
 'audionic9-542175-49576',
 'shoppers stop_AndroidOTGAdaptor-7',
 'sputnik_806/14A-8',
 'Rajesh_White Wax Vac Ear Cleaner',
 'Samsung Galaxy A7 710F (2016)',
 'casio_MTP-1183A-2ADF',
 'stitchers_TnT 034-L',
 'qzs_Blue Cotton Broad Neck T-shirt',
 'Apple iPhone 6S 16GB',
 'vitamin_Milk Thistle Liver Formula',
 'Q&Q_VW90-112Y',
 'emo_MK-19113-S',
 'Tiraaz_Tm-02-012-S',
 'Tiraaz_Tm-02-016-S',
 'Dynasty_Dynasty Spark-Royal Blue',
 'Dynasty_Dynasty Spark-French Blue',
 'Dynasty_Dynasty Spark-Brown',
 'Emo_SS-24020-42',
 'GBH_GS802-7',
 'Mochika_M0001129-10',
 'RS_Karachi Halwa Tin',
 'cr_AJWA DATES (400 GM)',
 'kcc_Sultanat Pocket Perfume',
 'Haier G20',
 'Eco Star_32U557',
 'Dany6-954217-555652',
 'kcc_lavender',
 'kkc_Fayha King Air Freshener',
 'kkc_Lavender King Air Freshener',
 'kcc_rose',
 'kcc_fresh',
 'west point_WF-306',
 'RS_Sohan Halwa_Tin-1000 GM',
 'Huawei P8 lite',
 'Audionic_LT-486',
 'ajmery_1-AJ',
 'alpina_Popcorn Maker SF-2608',
 'Haier M108',
 'Gree_24CZ8',
 'hol_A-406M-42',
 'Samsung Galaxy A3',
 'PHILIPS_HP8105_29',
 'RS_Baklawa 500gm',
 'RS_Nan Khatai',
 'philips_HD8323/01',
 'cr_ALMOND PLAIN-500 GM',
 'dawlance_Health Zone Plus 15 - 1 Ton Air Conditioner',
 'Audionic_B-880',
 'mm_AG-3017',
 'VITAMIN_VITA HAIR TREATMENT',
 'vitamin_Aloe Vera Plus',
 'audionic6-954217-562582',
 'MYWALET_MW-060-BROWN',
 'WE_MA14',
 'Teenz_E-1573',
 'AT-TT-2',
 'AT-MFNC-10',
 'BB_KIDSHD_PIR',
 'BB_KIDSHD_ BUL',
 'JBS_SL-STOR-031',
 'BO_nonRC-Jeep-Silver',
 'AUDIONIC BT110 SPEAKER',
 'sapil_Sapil Chichi Women 100ML',
 'AKL_A131128777_SS-33_Yellow',
 'Dany6-954217-691862',
 'kke_SCF690_17-A2P-global-001',
 'PucaM_SS-35-OLIVE BLACK-42',
 'ajmery_SYB-519-43',
 'Bold_Classic',
 'Bold_Active',
 'PucaM_atlas-grey-42',
 'Life source_GS300',
 'OPI_NLF16',
 'salience_SK101-L',
 'panasonic_3411',
 'UK_Cake Rusk Cardamom 150 Gms',
 'bb_WSTIV',
 'KI_bedsheet-2050mkmmbs',
 'Al Muhafiz Sohan Halwa Cashew',
 'audionic_AH-70',
 'Dawlance_MD 10 + DWB 600',
 'kcc_social',
 'kcc_smart',
 'Rajesh_RAJ001',
 'HR_Moong Dal 200g',
 'UK_Karachi Halwa Tin Pack 400 Gms',
 'emo_SS-17227-L',
 'sst_Jessy-Regular fit-Large',
 'BK5110500DG',
 'kcc_Charming Perfumed Talcum Powder-100gm',
 'sstop_etable',
 'sst_Logic 2-Slim Fit-Large',
 'samsung_ETA-U90JWSO_45',
 'AKL_GMTP002_Earth Red-L',
 'mm_AG-2049',
 'UC_PP-004-L',
 'liberty_9788174367181',
 'casio_MTP-1302D-1A1VDF',
 'Senorita_GAK-836-RED-34',
 'Dany_6954217552453',
 'dany_6954217942148',
 'kcc_funky',
 'Huawei_Y6 DS',
 'iPhone SE-16GB',
 '3m_NANOPAX',
 'Gasonline-MPT-524-BEIGE-36',
 'Ifsha_CU-0047',
 'UK_Namkino Badshahi Mix 200 Gms',
 'UK_Namkino Spicy Peanuts 200 Gms',
 'Tiraaz_Tm-02-019-L',
 'centrix_Scootify - Red Self Balancing Scooter',
 'Audionic  BT125 Speaker',
 'HOL_A-802T-39',
 'BB_RCKBS_GARD',
 'UK_Gift Box Habshi Halwa 500 Gms',
 'UK_Habshi Halwa Tin Pack 400 Gms',
 'UK_Pheni 400 Gms',
 'UC_SP-042-L',
 'emo_MJ-21916-36',
 'Gasonline-MPT-560-GREY-30',
 'AKL_A131128809_SS-87_Sea Green',
 'AKL_A131130523_SS-185_Blue',
 'AKL_A131128827_SS-118_Ivory',
 'nabila_Nchant FOR Olive',
 'AKL_DL-02-YELLOW',
 'UK_Namkino Chatkhara Papdi 150 Gms',
 'jackpot_JP-14',
 'RUB_Kingston_16 gb Sd Card',
 'B-power_8284384-42',
 'Emotions_Emo-BS-28436',
 'J&J_JJNR16',
 'J&J_JJPS-007XL',
 'J&J_JJNR12',
 'nabila_Ngage FOR Honey',
 'Truck Art Round metal tray',
 'CK_530-Vest-XLarge',
 'CK_530-Underwear-XLarge',
 'closecomfort_PC8',
 'edifier_XM6-PF',
 'qzs_Black V-Neck T-Shirt',
 'sm-SamsungC3520',
 'qzs_V-neck by QZS Clothing',
 'BO_4 Ft Sunset Glow Baby Swimming Pool',
 'RT002-M',
 'shubinak_SN-ERT-13-S - 34',
 'shubinak_SN-ERT-13-grey-S - 34',
 'AKL_A131128767_SS-25_Light Blue',
 'AKL_A131130507_SS-161_Blue',
 'Silkasia_Cream Stylish Embroidered Dress',
 'UK_ Namkino Lajawab Mix 200 Gms',
 'QMobile Bolt T50',
 'shubinak_SN-ERT-13-grey-M - 36',
 'kcc_bakheer',
 'bata_comfit-8744557-41-7',
 'JBS_WEN-043',
 'JBS_TAT-173',
 'Hstyle_HW-2016165',
 'emo_Emo-VB-12 Black Blazer',
 'vitamin_Ultra Gainer',
 'BK1010200BR',
 'UK_Gift Box Sohan Halwa 500 Gms',
 'UK_Gulab Jamun Tin Pack  1000 Gms',
 'AC_ac168-yellow',
 'Emo_SS-21775-41',
 'Hawks_A17',
 'urban_URT0023-L',
 'Bold_Fresh',
 'BK5110250OR',
 'BK5110500',
 'Infinix Hot Note X551-1GB-Gold-Nationwide Delivery',
 'Lenovo Zuk',
 'Nokia Asha 105',
 'bata_comfit-8613714-44-10',
 'bata_leena-5161226-37-4',
 'PucaM_SS-25-BLACK-41',
 'PucaM_SS-2715-CAMEL-43',
 'kkc_Rose King  Air Freshener',
 'AC_110-white with blacck',
 'hol_T-38-42',
 'Am-PTV_VC-1029-M',
 'Audionic_ LT-480 ',
 'sputnik_701/5-9',
 'B-power_8282391-43',
 'sputnik_701/D14-10',
 'Hstyle_HW-2016156',
 'Veet_1',
 'kcc_Harmony Perfumed Talcum Powder-200gm',
 'rute2_Vit B 50 Complex 50 Tablets',
 'vitamin_Ultra Whey Protein',
 'MYWALET_MW-033-D1-BLACK',
 'vitamin_Royal Jelly 500',
 'VITAMIN_HAIR SKIN & NAIL FORMULA',
 'VITAMIN_WHITENING BB CREAM',
 'alkhair_Black Seed Oil Softgel Capsules100  Cap bottle',
 'ESPICO_050-Fancy Nylon Bra-Black-34',
 'JBS_SL-STOR-017',
 'JBS_SL-STOR-051',
 'JBS_SL-STOR-024',
 'sputnik_177/9-10',
 'Audionic_DJ-106',
 'sputnik_3444/10-9',
 'ihijab_PN039',
 'ajwa_Ajwa Seeds Powder',
 'ajwa_Ajwa Dates Powder',
 'ESPICO_Classic Cotton-Skin-42',
 'samsung_EBF1A2GBU_8',
 'Ajmery_BRR-590-L',
 'HOS-m_DUNBM100',
 'HOS-m_DVFCWM125',
 'UK_Namkino Aaloo Sev 200 Gms',
 'HOS_HBDRW90',
 'PucaM_COOPER-NAVY-41',
 'sputnik_741/14-8',
 'Q&Q_RP00J002Y',
 'HR_Bombay Mixture 200g',
 'qzs_Black Mens V-neck T-shirt',
 'UK_ Cake Rusk Cardamom 700 Gms',
 'Audionic6-954217-516486',
 'RS_Nimcolia-5pack',
 'qzs_White V-Neck T-Shirt',
 'Bold_Noir',
 'QMobile Noir S3',
 'Rajesh_Pink Dora Electric Piano Keyboard',
 'Q MOBILE Noir X700 Pro',
 'Samsung_40J5200',
 'qzs_Silver Grey V-Neck Shirt',
 'LALA_LFK-10',
 'ESPICO_Seamless-Black-Free size',
 'OHT_LGW-13-Black',
 'Ctees_Teddy Love Keychain',
 'Salience_SS110-M',
 'sputnik_882/9-9',
 'Ifsha_CU-0051',
 'Apple iPhone 6 (16GB) Gold',
 'KI_bedsheet-2154',
 'R&I_eIcon Series 12000BTU',
 'kcc_mature',
 'Nokia 222',
 'Audionic_ B-800',
 'KC_209 White-XL',
 'J&J_JJNR8',
 'Maguari_TTHT-6',
 'Elite_EDF-89R',
 'Dawlance_DW-540 AF',
 'vitamin_Super Yohimbe 1000',
 'vitamin_Menopause Formula',
 'HR_Hara Chiwda 200g',
 'nabila_NGELIC FOR IVORY',
 'Veet_2',
 'cr_PUMPKIN SEEDS LARGE',
 'CK_730-Vest-Large',
 'CK_530-Underwear-Medium',
 'Turbo_100159',
 'redspot_9789810550127',
 'Audionic6-954217-517827',
 'samsung_B800BC_17',
 'kcc_New York',
 'kkc_Lemon Oasis Prickly Heat Powder',
 'AC_75',
 'KCC_OASIS LEMON',
 'ESPICO_Classic Cotton-Skin-32',
 'GBH-GL218-Fawn-11',
 'cr_PAN MASALA ( SWEET)-200 GM',
 'Samsung GALAXY NOTE-5',
 'Veet_12',
 'MEGUIAR_G9719',
 'MEGUIAR_M0716',
 'Atiqa_AO-3',
 'MYWALET_MW-001-D2-D-BROWN',
 'BO_DIY-Rc-Red',
 'BO_topspeedRC-black',
 'Farah_1-A',
 'PucaM_SS-2715-GREY-43',
 'AKL_A131130455_SS-145_Black',
 'Turk & Fillmore Lazaretto Tan-46-12',
 'sst_preservatif-Regular fit-Xlarge',
 'Nz_6006-XL',
 'Ajmery_BRR-590-XL',
 'shubinak_SM-WWB39-14-cargo-XL - 40',
 'renna_DC-DFB-GR',
 'redspot_9789696230007',
 'redspot_9789810445210',
 'redspot_9789810517397',
 'redspot_9789696230243',
 'Eglo_13359',
 'RUB_Rubian_Selfie Stick',
 'Audionic_LT-489',
 'Qmobile W15',
 'Q MOBILE Noir W35',
 'ajmery_TA-6',
 'stitchers_TnT 021-L',
 'stitchers_TnT 004-L',
 'Rumi_257-Brown-L',
 'Rumi_1024-Grey-L',
 'CITY_White Shirt Half Sleeves Prep to X-8 - 10 yrs - Size 26',
 'sputnik_133/14-8',
 'bata_leena-5615458-39-6',
 'Relaxsit_RS-57',
 'MYWALET_MW-007-BLACK',
 'QMobile Noir Z10',
 'Rajesh_RAJ57',
 'ihijab_PN037',
 'dawlance_Reddish DW-115CHZ White',
 'UK_Tea Rusk Sugar Free 220 Gms',
 'Ctees_Paris Keychain',
 'cr_ALMOND PLAIN-200 GM',
 'Dany_Powerbank Pb- 42 ',
 'cr_CASHEW NUT ROASTED-200 GM',
 'cr_PLUM IRANI (SWEET)-500 GM',
 'cr_FIG-200 GM',
 'cr_PEANUT ROASTED-200 GM',
 'cr_PISTA SALTED-200 GM',
 'J&J_JJWS-001',
 'J&J_JJCM-003',
 'Hstyle_HW-2016150',
 'Hstyle_HW-2016159',
 'Bjorn_WLBLBK005',
 'Audionic X-BOOM 5 Black',
 'vitamin_Prostate Support',
 'GFC_Ceiling V.I.P',
 'Fitbit_Surge',
 'kcc_Almas Pocket Perfume',
 'RB_VASJPLSF262005002-M',
 'AKL_A131128708_SS-8_Pink',
 'Turbo_100197',
 'YC_ODD-CHP-DIP-PLT',
 'Turbo_100184',
 'JBS_TAT-037',
 'L&L_LLHPL807',
 'noritake_NT4277M',
 'JBS_WEN-066',
 'kansai_Frosted Glass',
 'Turbo_100028',
 'tram_TT23081005',
 'Turbo_100120',
 'Turbo_100057',
 'Audionic_ B-770',
 'shopingmania_Ruby Necklace & Earrings Set',
 'sputnik_179/2-10',
 'Dany39525871458523879523',
 'AUDIONIC6-954217-548944',
 'MEGUIAR_G10307',
 'HR_Masala Moong Dal 200g',
 'BK1080200CF',
 'AM-Light Beige Suit APS-5100-Medium',
 'AM-Sky Blue Shalwar Suit APS-5100-Medium',
 'PucaM_SS-15-BROWN-44',
 'AM-White Cotton Shalwar Suit  AES-1067-Medium',
 'HP P1102 - White_18',
 'shoppers stop_MagicGlass-3',
 'AKL_A131130486_SS-183_Peach',
 'sputnik_701/D14-11',
 'Samsung Metro 312 SM-B312E',
 'redspot_9789696230144',
 'redspot_9789810841492',
 'redspot_9789696230106',
 'redspot_9810452144',
 'redspot_9789810780159',
 'redspot_9789810477189',
 'redspot_9789696230069',
 'redspot_9789696230205',
 'redspot_9789810517359',
 'redspot_9789696230137',
 'redspot_9810824280',
 'redspot_9810477198',
 'Q MOBILE Noir W50',
 'AKL_A131128810_SS-91_Green',
 'AKL_A131130512_SS-164_Grey',
 'amnaismail_AIL-377-B',
 'ajmery_AJ-123-XL',
 'QMobile Noir X350 White - LW',
 'BB_KIDSHD_PRI',
 'kcc_Social Pocket Perfume',
 'rute2_Coenzyme Q-10 ',
 'Life source_GM-300',
 'Lunar_smart',
 'HR_Nimbu Masala 200g',
 'CK_730-Vest-Medium',
 'mau_111033',
 'Emo_S-26858-42',
 'UC_Mustard-tt-S',
 'Hstyle_HW-2016175',
 'samsung_ETA-U90JWSL_42',
 'audionic6-954217-564364',
 'BB_KIDSHD_HORS',
 'PucaM_SS-2041-BLACK GREEN-41',
 'PucaM_STARZ-NAVY -44',
 'vitamin_Dark Circles',
 'vitamin_Vita Zinc',
 'osaka_24W SPIRAL',
 'noritake_NT4276M',
 'Karak_Honey 1 Kg',
 'Rubian_usb-fan-08',
 'bata_6616942-39-6',
 'CBS_9780071701723',
 'CBS_9780071464987',
 'Fpakistan_FP040',
 'mau_112936',
 'Dynasty_Marvel By Dynasty-Off-White',
 'Xenium_WA-201637',
 'kreations_VN 10-M',
 'Atiqa_ASLE-07',
 'pny_OU3 -32GB',
 'osaka_12.5W LED BULB',
 'qzs_black & charcoal V shirt',
 'AKL_A131128840_SS-44_Green',
 'AKL_A131128726_SS-63_Beige',
 'AKL_A131130488_SS-31_Peach',
 'Audionic_LT-488',
 'Audionic_Studio 4',
 'dynasty_Snow Berry-Black',
 'Teenz_E-H12',
 'vitamin_Ultra Muscle',
 'ihijab_CN017',
 'liberty_9780982423813',
 'Audionic_Rb 104',
 'scent_CALVIN KLEIN FRESH 75ML',
 'HOS_CKETW100',
 'J&J_JJNR19',
 'J&J_JJNR20',
 'osaka_5.5W LED BULB',
 'jackpot_JP-13',
 'kcc_summer',
 'PucaM_SS-2041-BLACK GREEN-42',
 'AKL_131699939_FMSG001-Dark Grey',
 'col qadri_Sentinels In The Sky',
 'PHILIPS_HAIR TRIMMER QC 5130/15',
 'RS_Sohan Halwa_Tin-450 GM',
 'Audionic_ECCO AH-715',
 'sre_Omnivoltaic',
 'Gasonline-MPT-205-MUSTARD-32',
 'Turbo_100157',
 'majestic_15 Pieces Cookware Set',
 'samsung_ETA-U90JWSN_44',
 'KI_bedsheet-2158',
 'L&S_meh006',
 'L&S_meh004',
 'kcc_Harmony Perfumed Talcum Powder-100gm',
 'Mochi_MW-723-GR',
 'vitamin_Grape Seed Antioxidant Formula',
 'Audionic X-BOOM 5 White',
 'Lunar Lr010',
 'ESPICO_Sports Bra-Black-Free size',
 'ESPICO_Seamless-Skin-Free size',
 'kcc_cool',
 'gree_12LM4',
 'ajmery_DE-2',
 'ajmery_CHD-109',
 'SA_302024-15.5',
 'Salience_SS111-L',
 'GG_RTW012-Large',
 'sst_Finch 2-Regular fit-Large',
 'vitamin_Acne Cream',
 'cn_clc_ AS-220RTS',
 'rebelz_Crazy Folk 6 Subjects Notebook',
 'Atiqa_AB-9',
 'mau_115173',
 'mau_117445',
 'mau_111041',
 'tcl_ 24 inch D2720 HD Ready LED TV',
 'sstop_iflashotg3in1',
 'vitamin_Vita Growth',
 'cr_CHAAR MAGHAZ',
 'cr_SOUNF (SWEET)',
 'bata_comfit-8647502-42-8',
 'Lunar Kb Expert Usb',
 'rute2_2820',
 'bata_comfit-8614096-40-6',
 'bata_comfit-8647502-44-10',
 'Audionic6-954217-519876',
 'vitamin_Acne Cure FaceWash',
 'ZM_NC1500',
 'Emo_HST-28676-XL',
 'cr_PLUM IRANI (SWEET)-200 GM',
 'vitamin_265 ',
 'emo_Emo-CS-28598-32',
 'samsung_EP-PG920I-S6_28',
 'ajmery_GRA-3-AJ-M',
 'Dynasty_York By Dynasty-Charcoal',
 'Dynasty_Marvel By Dynasty-Navy',
 'rute2_6060',
 'bata_comfit-8613714-42-8',
 'Philips HR1600_00',
 'Apple iPhone 6S Plus 128GB',
 'JBS_OMA-303',
 'JBS_OMA-137',
 'JBS_OMA-048',
 'JBS_ROS-076',
 'JBS_SZ-004',
 'Braun_Hair Straightener ES-1 ',
 'MACBOOK AIR 13-INCH 256 GB Flash Drive',
 'haier_24LK',
 'R&I_eInverter Series 18000BTU',
 'kkc_Electric Mosquito Destroyer Set',
 'BB_001',
 'JBS_TAT-187',
 'Veet_6',
 'Audionic9-542175-10682',
 'vitamin_Children Vitamins',
 'HR_Plain Bhujia 200g',
 'HR_Chilli Chatak Lachha 200g',
 'JBS_SL-STOR-039',
 'Q&Q_RP00J010Y ',
 'Xenium_PFF-2016140',
 'Life source_LS-5001',
 'Hstyle_HW-2016141',
 'kaliz_3 IN 1',
 'Emo_SS-21775-43',
 '3m_70005045094',
 "ISN's 100% Whey Protein Chocolate",
 'HR_Mint Lachha 200g',
 'HR_Kaju Mixture 200g',
 'Mochi_MW-703-CL Black',
 'kke_SCF68317',
 'Hawks_A41-Green-XL',
 'elite_EFP-402',
 'cr_NAAR DRY DATES(200GM)',
 'sputnik_749/D14-8',
 'vitamin_Eye Formula',
 'ajmery_SA-PP3',
 'kreations_VN 10-L',

In [86]:
data[data["Direccion"]=="nan"]

,Id_Item,Estado_Compra,Fecha,Direccion,Precio,Cantidad,Total,Id,Categoria_1,Comision,...,Metodo_Pago,Fecha_Trabajo,BI_Status,MV,Año,Mes,Cliente_Desde,M-Y,FY,Id_Cliente
14846,230008,canceled,2016-08-13,nan,0.0,1,0.0,100160070,\N,\N,...,cod,2016-08-13,Gross,0.0,2016,8,2016-8,8-2016,FY17,3468.0
20676,236830,canceled,2016-09-01,nan,0.0,1,0.0,100164902,\N,\N,...,cod,2016-09-01,Gross,0.0,2016,9,2016-8,9-2016,FY17,4369.0
39838,260006,canceled,2016-10-07,nan,0.0,1,0.0,100181136,\N,\N,...,cod,2016-10-07,Gross,0.0,2016,10,2016-7,10-2016,FY17,939.0
39839,260007,canceled,2016-10-07,nan,0.0,3,0.0,100181137,\N,\N,...,cod,2016-10-07,Gross,0.0,2016,10,2016-7,10-2016,FY17,939.0
39880,260061,canceled,2016-10-07,nan,0.0,3,0.0,100181174,\N,\N,...,cod,2016-10-07,Gross,0.0,2016,10,2016-7,10-2016,FY17,939.0
124968,367292,refund,2016-12-10,nan,0.0,1,0.0,100247863,\N,\N,...,cod,2016-12-10,Valid,0.0,2016,12,2016-11,12-2016,FY17,26305.0
125636,368122,refund,2016-12-12,nan,0.0,1,0.0,100248364,\N,\N,...,cod,2016-12-12,Valid,0.0,2016,12,2016-7,12-2016,FY17,2246.0
125811,368362,refund,2016-12-13,nan,0.0,1,0.0,100248497,\N,\N,...,cod,2016-12-13,Valid,0.0,2016,12,2016-7,12-2016,FY17,251.0
149597,399798,refund,2017-02-07,nan,0.0,1,0.0,100267148,\N,\N,...,cod,2017-02-07,Valid,0.0,2017,2,2017-2,2-2017,FY17,33062.0
170249,426105,canceled,2017-03-21,nan,0.0,1,6952.0,100281645,\N,\N,...,cod,2017-03-21,Gross,0.0,2017,3,2017-3,3-2017,FY17,38242.0
170401,426302,canceled,2017-03-22,nan,0.0,1,1873.0,100281748,\N,\N,...,cod,2017-03-22,Gross,0.0,2017,3,2017-3,3-2017,FY17,38278.0
173040,429392,refund,2017-03-23,nan,0.0,1,0.0,100283785,\N,\N,...,cod,2017-03-23,Valid,0.0,2017,3,2016-8,3-2017,FY17,4662.0
173045,429393,refund,2017-03-23,nan,0.0,1,0.0,100283786,\N,\N,...,cod,2017-03-23,Valid,0.0,2017,3,2016-8,3-2017,FY17,4662.0
173069,429421,refund,2017-03-23,nan,0.0,1,0.0,100283807,\N,\N,...,cod,2017-03-23,Valid,0.0,2017,3,2016-8,3-2017,FY17,4662.0
175411,432276,refund,2017-03-26,nan,0.0,1,0.0,100285563,\N,\N,...,cod,2017-03-26,Valid,0.0,2017,3,2016-11,3-2017,FY17,14625.0
238273,506324,canceled,2017-06-07,nan,0.0,1,0.0,100322823,\N,\N,...,cod,2017-06-07,Gross,0.0,2017,6,2016-11,6-2017,FY17,14905.0
316422,595858,cod,2017-10-12,nan,0.0,2,0.0,100367801,\N,0,...,cod,2017-10-12,Valid,0.0,2017,10,2017-8,10-2017,FY18,58333.0
325391,605726,order_refunded,2017-11-01,nan,18335.0,1,18335.0,100374250,Entertainment,\N,...,cod,2017-11-01,Valid,18335.0,2017,11,2017-11,11-2017,FY18,65343.0
325402,605740,canceled,2017-11-01,nan,16110.0,1,16110.0,100374259,Entertainment,\N,...,cod,2017-11-01,Gross,16110.0,2017,11,2017-11,11-2017,FY18,65350.0
325602,605954,order_refunded,2017-11-02,nan,16110.0,1,16110.0,100374382,Entertainment,C-RWP-31924,...,cod,2017-11-02,Valid,16110.0,2017,11,2017-11,11-2017,FY18,65366.0

In [87]:
data["Direccion"]=data["Direccion"].replace("nan","No Data")

In [88]:
data[data["Direccion"]=="nan"]

Empty DataFrame
Columns: [Id_Item, Estado_Compra, Fecha, Direccion, Precio, Cantidad, Total, Id, Categoria_1, Comision, Descuento, Metodo_Pago, Fecha_Trabajo, BI_Status, MV, Año, Mes, Cliente_Desde, M-Y, FY, Id_Cliente]
Index: []

[0 rows x 21 columns]

In [89]:
data["Id"]=[x.replace('-',"") for x in data["Id"]]
data["Id"]=data["Id"].astype(int)

In [90]:
data['Categoria_1'].unique().tolist()

["Women's Fashion",
 'Beauty & Grooming',
 'Soghaat',
 'Mobiles & Tablets',
 'Appliances',
 'Home & Living',
 "Men's Fashion",
 'Kids & Baby',
 '\\N',
 'Others',
 'Entertainment',
 'Computing',
 'Superstore',
 'Health & Sports',
 'Books',
 'School & Education',
 'nan']

In [91]:
data["Categoria_1"]=data["Categoria_1"].replace("nan","No Data")
data["Categoria_1"]=data["Categoria_1"].replace("\\N","No Data")

In [92]:
data['Categoria_1'].unique().tolist()

["Women's Fashion",
 'Beauty & Grooming',
 'Soghaat',
 'Mobiles & Tablets',
 'Appliances',
 'Home & Living',
 "Men's Fashion",
 'Kids & Baby',
 'No Data',
 'Others',
 'Entertainment',
 'Computing',
 'Superstore',
 'Health & Sports',
 'Books',
 'School & Education']

In [93]:
data['Comision'].unique().tolist()

['\\N',
 'R-FSD-52352',
 '105259',
 'R-KHW-104406',
 'R-FSD-58130',
 'C-PEW-104656',
 'C-Rwp-101853',
 'C-ISB-47491',
 'c-uet-44938',
 'C-RWP-103867',
 'R-KHS-104405',
 '104835',
 'C-ISB-105964',
 '865116',
 'C-ISB-40310',
 'C-ISB-102148',
 'C-RWP-102627',
 'R-PEW-41424',
 'C-MUX-33202',
 'C-KHS-44926',
 'C-RWP-66032',
 'C-RWP-31924',
 'C-MUX-106279',
 'C-MUX-43032',
 'R-LHW-105666',
 'C-PEW-105784',
 'C-MUX-48271',
 'C-KHS-31122',
 'R-KHS-103986',
 'C-MUX-100079',
 'C SKZ 41328',
 'C-RWP-41876',
 'C-RWP-47599',
 'C-FSD-41249',
 'C-RWP-102528',
 'C LHE 41938',
 'C-RWP-30884',
 'C-RWP-31520',
 'C-RWP-31691',
 'C SKZ 103997',
 'c-fsd-759',
 'C-MUX-R52221',
 '7828',
 'C-HDD-44781',
 'R-RWP-103991',
 '103996',
 'R-ISB-58059',
 'C-FSD-42225',
 'c-mux-47236',
 'C-ISB-103273',
 'C-MUX-52058',
 'R-PEW-50644',
 'C-MUX-31510',
 '80645',
 'C-MUX-7521',
 '51442',
 'C-MUX-20260',
 'R-isb-57478',
 'R-LHC-104132',
 'C LHE 40936',
 'R-KHS-103982',
 'C-ISB-42133',
 'C-ISB-84674',
 'C-KHC-34670',
 'C-MUX-30078',
 'C-FSD-43702',
 'R6596',
 'R-LHW-104137',
 'C-MUX-104110',
 'R-LHE-90613',
 'C-MUX-102023',
 'C-GUJ-52213',
 'C-MUX-105333',
 'C-MUX-104331',
 'R-LHC-104138',
 '80226',
 'C-MUX-48275',
 '0KNFM',
 'C_LHC_102999',
 '30071',
 'c-mux42203',
 'C-MUX-42203',
 '41078',
 'C-SKZ43603',
 'v',
 'C-PEW-33551',
 '3293',
 '105114',
 '60615',
 '101651',
 'C-ISB-102725',
 'C-ISB-43887',
 'R-LHW-103735',
 'C-MUX-51991',
 'R-PEW-104414',
 'C-FSD-104646',
 'C-KHS-43436',
 'C-PEW-103055',
 ' R-LHC-104412',
 'C-PEW-33745',
 '80702',
 'RWP-R-50687',
 '102795',
 'C-KHC-44247',
 'C-MUX-43033',
 'c-lhc-34292',
 'R-skz104411',
 'c-lhc-57595',
 '1151',
 'C-MUX-60389',
 'C-MUX-60384',
 '123123',
 'C-MUX-100374',
 'C-MUX-60390',
 '1072',
 'R-PEW-101268',
 'C-MUX-45345',
 '1234',
 '3118078',
 'r-hdd-70202',
 '80311',
 'MBC',
 '45254',
 'Aß',
 'C-HDD-40844',
 'C-PEW-34717',
 'C-UET-44938',
 '100572',
 'R103018',
 'R-KHS-104404',
 'R52346',
 'C-MUX-60385',
 'C-MUX-100111',
 'C-MUX-45342',
 'C-MUX-45338',
 'C-MUX-47458',
 'C-MUX-104107',
 'C-MUX-102808',
 'C-KHC-44287',
 'R-LHW-104415',
 'R-GUJ-105814',
 ' R-MUX-90516',
 '321',
 '90649',
 '101531',
 '45239',
 'C-ISB-34710',
 '42345',
 '41848',
 'R-GUJ-5095',
 'R-FSD-57661',
 'C-MUX-103608',
 'C-MUX-104911',
 'C-MUX-105781',
 'C-MUX-104310',
 'C-MUX-101662',
 'C-MUX-60391',
 'C-MUX-60386',
 'C-MUX-105516',
 'R-GUJ-102778',
 '30299',
 '1218',
 'Khw C-45144',
 'C-PEW-43877',
 'C_LHC_40935',
 'c-mux-47428',
 'C-MUX-20056',
 'C-MUX-100949',
 'c-mux-45349',
 'C SKZ 47454',
 '80211',
 'R-GUJ-105250',
 '105824',
 'Emo-Ps-28554',
 '11',
 'pew-41539',
 'C_Mux_33202',
 'R80763',
 '30967',
 'Rwp-90927',
 'GUJ-102771',
 'C-MUX-47614',
 'C-GUJ-106193',
 'C-MUX-104970',
 'C-GUJ-42532',
 'C-LHC-34292',
 'R-UET-50615',
 'R-KHC-50744',
 'R-Guj-51944',
 'C-LHC-40161',
 'C-MUX-43685',
 'R - KHS - 104404',
 'C-ISB-30197',
 'C-KHIW-30222',
 'C-ISB-31526',
 '70325',
 'C-LHC-41800',
 'R_RWP_30884',
 'C-LHC-42648',
 'R-Isb-58059',
 'C-KHS-33400',
 'C-KHS-44322',
 'C-GUJ-44347',
 'C-KHS-31943',
 'C-57551-RWP',
 'C-ISB-102525',
 'C-MUX-51202',
 'C-FSD-42180',
 'C-PEW-46117',
 'C-LHC-30667',
 'C-LHC-41942',
 'C-LHC-31085',
 'peer baba',
 'C-KHE-34256',
 'C-FSD-41440',
 'C-LHC-42722',
 'C-LHC-47480',
 'C-LHC-103204',
 'C-LHC-42935',
 'C-LHC-30373',
 'C-LHC-33817',
 'C-LHC-42241',
 'C-LHC-100971',
 'C-LHC-40278',
 'C-LHC-103208',
 'C-LHC-31455',
 'C-LHC-101518',
 'C-LHC-30695',
 'C-LHC-33105',
 'C-LHC-31542',
 'C-LHC-40347',
 'C-LHC-47612',
 'C-KHIW-30261',
 'C-LHC-30384',
 'C-LHC-102032',
 'R-KHS104356',
 'C-KHS-30313',
 'C-KHS-47999',
 'C-FSD-102007',
 'C-ISB-44714',
 'C-KHC-44097',
 '80212',
 ' LHW 103447',
 'C-LHC-30707',
 'C SKZ 51377',
 'C-GUJ-100103',
 'R--GUJ-106370',
 '987',
 'C-MUX-52221',
 'C-KHS-105150',
 '57533',
 'C SKZ 100913',
 'C SKZ100913',
 '7747',
 'C-GUJ-100025',
 'C-MUX-57524',
 'C-LHC-30575',
 '110',
 'C-KHIW-31558',
 'C-KHE-45611',
 'C-KHE-31910',
 'C-FSD-45407',
 'C-KHE-32038',
 'C-KHIW-31922',
 'C-GUJ-44840',
 'C-LHC-30924',
 'c-hdd-44686',
 'R-MUX50092',
 'C-FSD-100822',
 'C-LHC-30404',
 '45929',
 'C-MUX102551',
 'ABEST125',
 'ABEST189',
 'R104413',
 '295',
 'R-LHC-104417',
 'R-LHE-104418',
 'C-FSD - 47223',
 'C-PEW-41945',
 'C-RWP-47597',
 'C-FSD-47877',
 'R70504',
 'C-FSD-30642',
 'C-MUX-3969',
 'C-KHIW-30768',
 'C-KHC-44297',
 'C-KHC-104496',
 'C-KHIW-30246',
 'C-KHIW-33503',
 '34737',
 'C-LHC-102999',
 'C-KHS-44328',
 'C_MUX_51613',
 'R-KHE-103983',
 'C-KHIW-31860',
 '3007375795',
 'C-ISB-31457',
 'C-LHC-32916',
 'C-LHC-31223',
 'C-LHC-43842',
 'C-LHC-42342',
 'C-KHC-44296',
 'C-LHC-102996',
 'C-LHC-42483',
 'C-LHC-30772',
 'C-LHC-31130',
 'C-LHC-104077',
 'C-FSD-45107',
 'C-KHC-44376',
 'R-MUX 20055',
 'c-rwp-30884',
 'C-KHC-47854',
 'C-LHC-30725',
 'C-LHC-103422',
 'C-LHC-102055',
 'C-LHC-33911',
 'C LHE 51782',
 'C-KHC-33771',
 'C-MUX-105451',
 'C-KHC-42765',
 'C-KHIW-30621',
 'c-mux-45373',
 '800',
 'C-MUX-34932',
 'C-MUX-41256',
 'C-ISB -30197',
 'C-KHE-34963',
 'C-RWP-103478',
 'C-FSD-42083',
 'C-FSD-32557',
 'C-FSD-43701',
 'CSKZ',
 'C-MUX-48107',
 'C-LHC-40935',
 'C-KHE-40534',
 'C-FSD-44807',
 'C-RWP-1361',
 'C-FSD-7756',
 'c-mux-70510',
 'khs-52070',
 'R90513',
 'C-ISB-41578',
 '50127',
 'C-FSD-104647',
 'C-FSD-100305',
 '41539',
 'C-FSD-48268',
 'C-FSD-42009',
 'C-FSD-103427',
 '151311',
 '104245',
 'C-KHC-101486',
 'C-KHC-100070',
 'C-KHC-42631',
 'C-KHC-45574',
 'C-LHC-43141',
 'C-LHC-101861',
 'C-KHIW-102793',
 'C-LHC-42544',
 'C-LHC-104538',
 'C-LHC-47423',
 'C-MUX-51335',
 'c-rwp-104245',
 'YAYVO.COMBY TCS',
 'C SKZ 34816',
 'C-KHC-101899',
 'C_LHC_90609',
 'C_LHC_32916',
 '102348',
 'C-FSD-102594',
 'C-FSD-42199',
 'C-KHIW-30226',
 'C-ISB-105617',
 'C-FSD-1000137',
 'C-FSD-45709',
 'C-FSD-47768',
 'C-FSD-101824',
 'C-MUX-7930',
 '33030',
 'C-MUX-52031',
 'C-MUX-57746',
 '33503',
 'C-FSD-44806',
 'C-ISB-105907',
 'C-ISB-104116',
 'RWP-C-45720',
 'C-LHC-30406',
 'C-LHC-100380',
 '45380',
 'C-MUX-50092',
 'C-ISB-40422',
 '502084485',
 'C-KHIW-32154',
 'C-KHIW-102756',
 'R_MUX_105458',
 'C-MUX-20055',
 '1022001',
 'C-GUJ-45815',
 '48095',
 '101654',
 '9984',
 '101414',
 'C-HDD-105008',
 '4391a',
 'C-GUJ-100603',
 'C-FSD-105091',
 'C-FSD-104568',
 'C-RWP-66018',
 'c-fsd-32134',
 'C-FSD-44034',
 'C-ISB-43933',
 'C-LHC-34286',
 'C-LHC-33644',
 'R/70304',
 'C-LHC-30402',
 '3.0602E+11',
 'C-LHC-42546',
 'C-GUJ-105018',
 'C-ISB-105895',
 'C-ISB-44435',
 'C-KHS-32497',
 'C-KHIW-43069',
 'R-GUJ-104007',
 'R-LHC-104412',
 'C-KHE-43130',
 'C-KHE-41916',
 '421',
 'C-FSD-105382',
 'R-HDD-106533',
 'c-52484',
 'C-Rwp-31924',
 'c-mux-20056',
 'C-KHC-44240',
 'C-ISB-41886',
 'C-KHC-42624',
 'C-ISB-44443',
 'C-KHC-43402',
 'C-ISB-103167',
 'C-KHC-102758',
 'C-RWP-1232',
 'C LHE 30399',
 'C-MUX-45335',
 'C-ISB-30198',
 '57148',
 'C SKZ 105566',
 'c-mux51265',
 'C-RWP-57551',
 'R-RWP-90906',
 'C-MUX-51837',
 'R70210',
 'C-KHE-32368',
 'C-FSD-70714',
 'C-FSD-45708',
 'C-FSD-45706',
 'C-ISB -84633',
 'C-KHIW-43746',
 'c-fsd-5446',
 '103563',
 'C-MUX-44984',
 'C-KHIW-40765',
 '1111',
 'C-ISB-84637',
 'C-ISB-84721',
 'C-ISB-102279',
 'R-HDD-105008',
 'C-ISB-103475',
 'C-ISB-84759',
 '1063653873',
 'C-LHC-40362',
 'C-ISB-102714',
 'C-LHC-30874',
 'C-ISB-43339',
 'C-RWP-104250',
 '30637',
 'C-ISB-102715',
 'C-ISB-105153',
 '307',
 'C-GUJ-105901',
 'c_isb_104133',
 'C-KHC-44238',
 'C-KHIW-43409',
 'C-HDD-45296',
 'C SKZ 2825',
 'C-HDD-101444',
 '80513',
 'C SKZ 43904',
 '103055',
 '105611',
 '12312',
 'C-KHE-41912',
 'c-fsd-47478',
 'c-fsd-58125',
 '43754',
 'C-ISB-40692',
 'C-ISB-44028',
 'C-MUX-33465',
 'r-pew-41424',
 'C SKZ 45320',
 'C SKZ 0576',
 'C-KHIW-30252',
 'C SKZ 105363',
 'C SKZ 45319',
 'C SKZ 45260',
 'C SKZ 70334',
 'C SKZ 41997',
 'C SKZ 104522',
 'R-MUX-R52221',
 'C-ISB-31205',
 'R-RWP-90946',
 'C-R70303',
 'C-ISB-102713',
 'R-MUX-104416',
 'C SKZ 47876',
 'C SKZ 80315',
 '104521',
 'C-GUJ-105879',
 'C-RWP-2108',
 'C-RWP-66058',
 'C-RWP-30006',
 'C-GUJ-41235',
 '11507643',
 'C-GUJ-33212',
 'C-GUJ101944',
 'C-GUJ-101944',
 'C-GUJ-100808',
 'C-KHS-47788',
 'C-ISB-31383',
 'R-KHW-104407',
 'C-MUX-104104',
 'C-KHC-101297',
 'R-GUJ-57220',
 'C-KHC-43407',
 'C-ISB-31073',
 'C-GUJ-51957',
 'c-uet-43565',
 'C-FSD-43228',
 'C-KHIW-40518',
 'C-KHIW-30295',
 'irfanullah',
 'LHC-31082',
 '5.74568E+11',
 '102834',
 'C-RWP-66064',
 'C-FSD-105782',
 'R-KHS-57483',
 'cskz40330',
 'crkz100345',
 'R-90513-MUX',
 'C SKZ 70324',
 'C SKZ 70327',
 'C SKZ 34072',
 'CSKZ 103437',
 'NAU8541',
 'C-MUX-45383',
 '33192',
 '534282108',
 'hdd-40968',
 '884',
 '0',
 'C-RWP-41553',
 'C-RWP-3277',
 'C-RWP-103851',
 'C-RWP-104730',
 'C-RWP-66065',
 'C-MUX-30073',
 'C-HDD 100832',
 'C-MUX-50941',
 'C--MUX-50941',
 'C-MUX-44033',
 'C-LHC-41517',
 'Cap skz106132',
 'C-ISB-32554',
 'Cap skz42821',
 'C-ISB-40033',
 'C-ISB-32536',
 'Cap skz104351',
 'Cap skz101076',
 'C-ISB-105300',
 'C-KHIW-30302',
 'C-MUX-45489',
 'C-MUX-100378',
 'C-MUX-100300',
 'C-MUX-101873',
 'C-MUX-6682',
 'C-MUX-45483',
 'C-MUX-101370',
 'C-MUX-35356',
 'C-MUX-52151',
 'C-MUX-101875',
 'C-MUX-7995',
 'C-MUX-45351',
 'C SKZ 30473',
 'C SKZ 43670',
 '90110',
 'C SKZ 47659',
 'C SKZ 32101',
 'C SKZ 45313',
 'C SKZ 70332',
 'C-MUX-51985',
 'C-ISB-102728',
 'C-mux-48107',
 'C-HDD-45298',
 'C-MUX-50938',
 'C-MUX-43738',
 'C-ISB-43545',
 'R-MUX-104361',
 'R - KHS - 104404 NB',
 '58156',
 'C-ISB-104043',
 'C-FSD-33799',
 'cskz41420',
 'C-ISB-33136',
 'C-MUX-43783',
 '8',
 'C-ISB-84716',
 'C-ISB-42045',
 'R-RWP-90944',
 'R',
 'fgh',
 'peerbabafarooq.com',
 'C-GUJ-104123',
 'C-ISB-32998',
 'C-GUJ-103253',
 'C-LHC-104304',
 'C-GUJ104123',
 'C-ISB-84659',
 'C-ISB-84634',
 'C-ISB-104135',
 'C-ISB-102723',
 'C-ISB-103074',
 'C-ISB-84657',
 'C-ISB-104467',
 'C-LHC-31082',
 'C_LHC_30667',
 '100215',
 'R-RWP-105570',
 'pakistan',
 'C-ISB-104133',
 'C-RWP-106404',
 '58059',
 'C-MUX-45738',
 '104123',
 'C-ISB-103638',
 'C SKZ42824',
 'C SKZ 30479',
 'C-ISB-45617',
 'C SKZ 30478',
 'C SKZ 31232',
 'C SKZ 42116',
 'C SKZ 42824',
 'C SKZ 47247',
 'C SKZ 102089',
 '104656',
 'C SKZ 100996',
 'C-MUX-R70503',
 'C SKZ 42822',
 'C-ISB-100868',
 'C-MUX-16258',
 '111',
 'LHE-51072',
 'C-MUX-47429',
 'C-ISB-100597',
 'C-ISB-100712',
 'C LHE 30366',
 'C-ISB-103446',
 'R-FSD-104419',
 'C-ISB -84637',
 'C-KHIW-33030',
 '12345',
 'cpw-103055',
 'R-RWP-90920',
 'C-ISB-47265',
 'C-ISB-47488',
 'C-RWP-44769',
 'R-MUX-90507',
 'C SKZ 101124',
 'CUET 43234',
 'C-KHIW-40393',
 'C-MUX-45373',
 'C-KHS-47843',
 'C-KHS-104499',
 'C-KHS-101854',
 'C-KHIW-105616',
 '57248',
 'r-pew-50644',
 '102999',
 '45366',
 'C-LHC-42545',
 'c-rwp-2801',
 'C-RWP-2801',
 'c-fsd-31097',
 '52107',
 'C-KHS-42567',
 'R-GUJ-106370',
 '80767',
 'C-ISB-104227',
 'C-MUX-51359',
 'C-ISB-105965',
 'C-GUJ-33192',
 'C-ISB-103710',
 'C-KHS-40449',
 'C-ISB-40166',
 'C-ISB-102735',
 'C-KHS-48008',
 'C-ISB -103167',
 'C-GUJ-100325',
 'C-ISB -102714',
 'C-ISB -84721',
 'C-ISB-84658',
 'C-KHS-103012',
 'C-ISB-101121',
 'C-ISB-101119',
 '51526',
 'C-KHS-41952',
 'R51526',
 'C-ISB-41157',
 'C-ISB-42280',
 'C-ISB-48224',
 'C-ISB-101487',
 'C-ISB-42692',
 'C-KHIW-30274',
 'C-ISB-32214',
 'C-ISB-42986',
 'C-ISB-30219',
 'C-MUX-14683',
 'C-MUX-40944',
 'C-MUX-47459',
 'C-MUX-30080',
 'C-KHS-44307',
 'C-KHS-48296',
 'C-KHS-100008',
 'SKZ C 47876',
 'C98B',
 '103274',
 'C-KHC-102564',
 'C-LHC-105089',
 'C-ISB-104441',
 'C-ISB-102962',
 'C-KHC-41396',
 '34325',
 'C-ISB -102728',
 'C-ISB-84736',
 'C-ISB-102729',
 'C-KHS-102192',
 'C-KHS-44308',
 'C-KHS-44329',
 'R-RWP-90909',
 'CC_Fsd 104646',
 'AG-4027',
 '105008',
 '20081',
 'C LHE 41720',
 'C_SKZ43603',
 'C-LHC-106237',
 'C-ISB-48223',
 'C-FSD-51667',
 'KHE-103411',
 'C-MUX-100376',
 'C-MUX-52116',
 'C SKZ 70304',
 'C-KHS-45198',
 'C-MUX-4026',
 'C-FSD-103912',
 'C-LHC-3429',
 'C-PEW-32935',
 'R-GUJ-100905',
 'Combed-004',
 'C-FSD-47223',
 'C',
 'R-GUJ-102781',
 'SKZ 34856',
 'C-GUJ-103015',
 '105810',
 'R-HDD 105008',
 'C--PEW-51830',
 'C-FSD-105093',
 'Combed-008',
 'MCD-017, MCD-028',
 'C-RWP-45720',
 'guj-7674',
 'R-GUJ-52164',
 'C-GUJ100603',
 'R-GUJ-102197',
 'C-GU-100025',
 'C-ISB-106190',
 'C-ISB-33958',
 '43702',
 'C-ISB-44695',
 'C-KHS-104692',
 '45229',
 'C-PEW-50683',
 '106534',
 'r-rwp-90944',
 'R-GUJ-52013',
 '48071',
 '70327',
 '34099',
 'C-MUX-101198',
 'C-MUX-31202',
 'C-MUX-33285',
 'C-MUX-44753',
 'c-uet-47342',
 'C-LHC-100123',
 'C-LHC-102798',
 '70310',
 'R-ISB-57478',
 'C-FSD-33835',
 'C-LHC-44865',
 'C-LHC-30892',
 'Q',
 'R-HDD-106534',
 'C-PEW-52023',
 'C LHE 100318',
 'C LHE 102670',
 'C LHE 7905',
 '90918',
 'R-GUJ-57238',
 'C LHE 105674',
 'R-MUX-105462',
 'R-RWP52008',
 '105546',
 'R-GUJ-103546',
 'C-ISB-100709',
 'C-ISB-31074',
 'C-ISB-102737',
 '105666',
 'C-LHC-42021',
 '14857',
 'R51294',
 'cfsd100048',
 'cfsd43149',
 'cfsd43702',
 '3366786786',
 'rfsd100059',
 'cfsd45578',
 'C SKZ 103437',
 'cfsd41177',
 'rfsd627',
 'C-PEW-45043',
 'ops101371',
 'C-GU-2585',
 'cfsd104897',
 'ops105990',
 '80203',
 'C-GU-105651',
 'C-GU-51957',
 'C-GUJ-80925',
 'C-KHC-40913',
 'C LHE 101997',
 'c-uet-41597',
 'C-GUj-41235',
 'C-FSD-50421',
 'C-GUJ-45614',
 'r7210',
 '101824',
 'C-LHC-104915',
 'R-RWP103592',
 'C-KHS-47841',
 'C-KHS-48006',
 '52384',
 'GTI/103026',
 '45709',
 'gti70330',
 'C-KHS-42572',
 'R90515',
 'C-FSD -32556',
 'C-RWP-104245',
 'C-ISB-34076',
 'C-MUX-57998',
 'GTI/70304',
 'C-MUX-41182',
 'C-FSD-32134',
 'C-FSD-31086',
 'C-FSD-51724',
 'C-FSD-6006',
 'C-FSD-41251',
 'C LHE 104143',
 'C-FSD-31097',
 'HDD-45229',
 '47645',
 'C-uet-44938',
 'c-mux-45345',
 '7780',
 '44396',
 '100952',
 '102015',
 'C-FSD-100202',
 'R-RWPX26113',
 'R-SKZ70303',
 'MUX-7245',
 '57149',
 'C-KHS-41834',
 'O21',
 'C-LHC-103873',
 'R-RWP101411',
 'C-ISB-41555',
 'C-KHS-32782',
 'c-uet-104388',
 'C-FSD-627',
 '50243',
 '101527',
 '45593',
 '52139',
 '100128',
 'C SKZ 30969',
 'R SKZ 104411',
 '102538',
 '100923',
 'R SKZ 70334',
 '41038',
 '2256',
 '106324',
 '41657',
 'R SKZ 70315',
 'C-80715-MUX',
 'C-41182-MUX',
 'C SKZ 34793',
 '47647',
 'C SKZ 45138',
 'C-MUX103889',
 'C-MUX-103889',
 '35263',
 '104901',
 '45595',
 '41895',
 'C-GU-100603',
 'C-GUj-105901',
 'C-GUJ-104725',
 'C-GUJ-106384',
 'C-ISB-32985',
 'C-FSD-47644',
 'C-PEW-33480',
 'c-uet-100794',
 '40618',
 'C-MUX-6821',
 '105162',
 'GPBDL',
 '105540',
 '31086',
 'C-fsd-105468',
 'C-GUJ-7674',
 'C-GUJ-105651',
 'C-GUJ-57446',
 'C-GUJ-106399',
 'C-LHC-40222',
 'C-ISB-105950',
 'C-KHIW-30307',
 'C-ISB-40420',
 'C-KHS-47794',
 'C-KHS-47332',
 'C-LHC-102355',
 'C-LHC-30364',
 'C-LHC-30377',
 'CFSD43702',
 'C-LHC-30964',
 'C-LHC-33240',
 'C-LHC-34014',
 'C-KHC-33053',
 'C-LHC-40931',
 'C-LHC-41891',
 'C-KHS-44745',
 'C-KHS-40514',
 'C-FSD- 105782',
 'c-uet-4493881',
 'C-KHS-44320',
 'C-FSD-57156',
 'C-FSD-102460',
 'C-KHS-45785',
 'C-KHC-32706',
 'c-hdd-45292',
 'C-KHS-33057',
 'C-KHS-32789',
 'C-UET-44107',
 '34012',
 'C.FSD.6813',
 '104684',
 'c-mux-104684',
 '7045',
 '106469',
 '6199',
 'C LHE100318',
 'CHDD40190',
 'C-RWP-104424',
 'R90511',
 'R-MUX-52221',
 'M-MUX-45351',
 'C-HDD-40618',
 'C-ISB 30204',
 'C-MUX-30081',
 'C-HDD-102201',
 'C-HDD-70208',
 'C-HDD-45297',
 'c-mux100368',
 'C-MUX-33574',
 '13',
 'C SKZ 106105',
 'C SKZ 106102',
 'C SKZ 106130',
 'C SKZ  102089',
 ...]

In [94]:
data["Comision"]=data["Comision"].replace("nan","No Data")
data["Comision"]=data["Comision"].replace("\\N","No Data")

In [95]:
data['Metodo_Pago'].unique().tolist()

['cod',
 'ublcreditcard',
 'mygateway',
 'customercredit',
 'cashatdoorstep',
 'mcblite',
 'internetbanking',
 'marketingexpense',
 'productcredit',
 'financesettlement',
 'Payaxis',
 'jazzvoucher',
 'jazzwallet',
 'Easypay',
 'Easypay_MA',
 'easypay_voucher',
 'bankalfalah',
 'apg']

In [96]:
data['BI_Status'].unique().tolist()

['#REF!', 'Gross', 'Net', 'Valid']

In [97]:
data["BI_Status"]=data["BI_Status"].replace("#REF!","No Data")

In [98]:
data['BI_Status'].unique().tolist()

['No Data', 'Gross', 'Net', 'Valid']

In [99]:
data['Cliente_Desde'].unique().tolist()

['2016-7',
 '2016-8',
 '2016-9',
 '2016-10',
 '2016-11',
 '2016-12',
 '2017-1',
 '2017-2',
 '2017-3',
 '2017-4',
 '2017-5',
 '2017-6',
 '2017-7',
 '2017-8',
 '2017-9',
 '2017-10',
 '2017-11',
 '2017-12',
 '2018-1',
 'nan',
 '2018-2',
 '2018-3',
 '2018-4',
 '2018-5',
 '2018-6',
 '2018-7',
 '2018-8']

In [100]:

data["Cliente_Desde"]=data["Cliente_Desde"].replace("nan","No Data")

In [101]:
data['M-Y'].unique().tolist()

['7-2016',
 '8-2016',
 '9-2016',
 '10-2016',
 '11-2016',
 '12-2016',
 '1-2017',
 '2-2017',
 '3-2017',
 '4-2017',
 '5-2017',
 '6-2017',
 '7-2017',
 '8-2017',
 '9-2017',
 '10-2017',
 '11-2017',
 '12-2017',
 '2-2018',
 '1-2018',
 '3-2018',
 '4-2018',
 '5-2018',
 '6-2018',
 '7-2018',
 '8-2018']

In [102]:
data["FY"].unique().tolist()

['FY17', 'FY18', 'FY19']

In [103]:
data["Id_Cliente"]=data["Id_Cliente"].replace(data["Id_Cliente"][427378],"0")
data["Id_Cliente"]=data["Id_Cliente"].astype(float)
data["Id_Cliente"]=data["Id_Cliente"].astype(int)

In [104]:
max(data["Id_Cliente"])

115326

In [105]:
for i in range(len(data["Id_Cliente"])):
  if data.loc[i,"Id_Cliente"]==0:
      data.loc[i,"Id_Cliente"]=max(data["Id_Cliente"])+1

In [106]:
max(data["Id_Cliente"])

115337

In [107]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 584524 entries, 0 to 584523
Data columns (total 21 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Id_Item        584524 non-null  int64
 1   Estado_Compra  584524 non-null  object
 2   Fecha          584524 non-null  object
 3   Direccion      584524 non-null  object
 4   Precio         584524 non-null  float64
 5   Cantidad       584524 non-null  int64
 6   Total          584524 non-null  float64
 7   Id             584524 non-null  int64
 8   Categoria_1    584524 non-null  object
 9   Comision       584524 non-null  object
 10  Descuento      584524 non-null  float64
 11  Metodo_Pago    584524 non-null  object
 12  Fecha_Trabajo  584524 non-null  object
 13  BI_Status      584524 non-null  object
 14  MV             584524 non-null  float64
 15  Año            584524 non-null  int64
 16  Mes            584524 non-null  int64
 17  Cliente_Desde  584524 non-null  object
 18  M-Y            584524 non-null  object
 19  FY             584524 non-null  object
 20  Id_Cliente     584524 non-null  int64
dtypes: float64(4), int64(6), object(11)
memory usage: 114.2+ MB

In [108]:
Estado_Compra=pd.DataFrame(data["Estado_Compra"].unique(), index=range(1,17), columns=["Estado_Compra"])
Estado_Compra.to_csv("Estado_Compra.csv",index=True)

In [109]:
Metodo_Pago=pd.DataFrame(data["Metodo_Pago"].unique(), index=range(1,19), columns=["Metodo_Pago"])
Metodo_Pago.to_csv("Metodo_Pago.csv",index=True)

In [110]:
Categoria=pd.DataFrame(data["Categoria_1"].unique(), index=range(1,17), columns=["Categoria_1"])
Categoria.to_csv("Categoria.csv",index=True)

In [112]:
Columnas=["Id","Id_Item","Estado_Compra","Fecha","Categoria_1","Id_Cliente","Precio","Cantidad","Descuento","Metodo_Pago","Fecha_Trabajo","Total"]
Venta=pd.DataFrame(data[Columnas],index= range(1,len(data)), columns=Columnas)
Venta.to_csv("Venta.csv",index=True)